### ISSUE TITLE
About the test results

### ISSUE THREAD

**Issue by CGYDSB** [Toytiny/milliFlow#10]
hi, I used the dataset (https://drive.google.com/file/d/1cfIdR63Plt546mOiHxGMlgg2cgy4a_HL/view?usp=drive_link)
and the model you gave for testing, but the metrics are much different from those in the paper
###The mean epe: 0.04266031415997727###
###The mean accs: 0.9405251966555459###
###The mean accr: 0.9656738615344209###

**Comment by Lan555** [comment]
You can add move epe and static epe by
'''
dis = torch.norm(gt_f, dim=2)
move_idx = torch.nonzero((dis>0.01), as_tuple=False)
move_pred = torch.index_select(pred_f, dim=1, index = move_idx[:, 0])
move_gt = torch.index_select(gt_f, dim=1, index = move_idx[:, 0])
move_gt = move_gt.cpu().numpy()
move_pred = move_pred.cpu().numpy()
move_error = np.sqrt(np.sum((pred - gt_f) ** 2, 2) + 1e-20)/10
move_epe = np.mean(move_error)
'''
