### ISSUE TITLE
About training and test

### ISSUE THREAD

**Issue by xlbjy** [Toytiny/milliFlow#4]
Hi, I would like to reproduce the experiment. Can you provide training and testing instructions? And configuration files can be provided? For example, configs.yaml. Thank you.

**Comment by Toytiny** [comment]
Hi, thanks for reaching out! We will update our guideline soon.

**Comment by jianbo-shang** [comment]
> Hi, thanks for reaching out! We will update our guideline soon.

Thanks, I would also like to reproduce your code, I hope you can write it in detail, thanks again!

**Comment by wdurhamh** [comment]
Hello - I am also interested in reproducing this code. It seems like a great project, but I've run into the same issue (no configs.yaml file). Should we expect any updates to the repo?

**Comment by Toytiny** [comment]
Hi, we are working for a deadline for now, and will update the guideline ASAP. The easiest time is next week. Please stay tuned for update.
