### ISSUE TITLE
Problem encountered while running evaluation

### ISSUE THREAD

**Issue by Emery-Wang** [Toytiny/milliFlow#6]
Thank you for open sourcing such a great project.
But I've had a problem while trying to evaluate the model I trained.

python main.py --dataset_path data/ --exp_name mmflow1  --model mmflow --dataset ClipDataset
{'exp_name': 'mmflow', 'model': 'mmflow', 'num_points': 128, 'batch_size': 16, 'val_batch_size': 16, 'epochs': 15, 'lr': 0.001, 'decay_epochs': 1, 'decay_rate': 0.9, 'cuda_device': '1', 'no_cuda': False, 'seed': 1234, 'num_workers': 8, 'eval': True, 'eval_split': 'val', 'val_split': 'test', 'dataset': 'ClipDataset', 'train_set': 'train', 'extra_percent': 0.4, 'dataset_path': 'data/', 'aug': False, 'vis': False, 'save_res': True, 'rigid_thres': 0.15, 'vr_thres': 0.3, 'stat_thres': 0.5, 'mini_clip_len': 5, 'update_len': 5, 'load_checkpoint': True, 'model_path': 'checkpoints/mmflow/models/model.best.t7', 'joint_train': False}
checkpoints/mmflow/models/model.best.t7
Successfully load model parameters!
 40%|██████████████████████████████████████████████████████████████████▏                                                                                                 | 2906/7199 [04:42<06:56, 10.30it/s]
Traceback (most recent call last):
  File "main.py", line 451, in <module>
    main()
  File "main.py", line 434, in main
    test(args, net, test_loader,textio)
  File "main.py", line 171, in test
    sf_metric = test_one_epoch_seq(args, net, test_loader, textio)
  File "/root/autodl-tmp/milliFlow-main/clip_util.py", line 455, in test_one_epoch_seq
    pred_f, gfeat = net(pc1, pc2, ft1, ft2, gfeat)
  File "/root/autodl-tmp/conda/envs/flow/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/milliFlow-main/models/mmflow_t.py", line 132, in forward
    final_features, gfeat = self.Backbone(pc1,pc2,feature1,feature2, gfeat_prev)
  File "/root/autodl-tmp/milliFlow-main/models/mmflow_t.py", line 104, in Backbone
    cor_features = self.fc_layer(pc1, pc2, pc1_features, pc2_features)
  File "/root/autodl-tmp/conda/envs/flow/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/milliFlow-main/utils/model_utils/radarflow_util.py", line 208, in forward
    knn_idx = knn_point(self.nsample, xyz2, xyz1) # B, N1, nsample
  File "/root/autodl-tmp/milliFlow-main/utils/model_utils/radarflow_util.py", line 98, in knn_point
    _, group_idx = torch.topk(sqrdists, nsample, dim = -1, largest=False, sorted=False)
RuntimeError: invalid argument 5: k not in range for dimension at /opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/THC/generic/THCTensorTopK.cu:26

Here are the package I've installed
Package              Version
-------------------- ---------------
addict               2.4.0
attrs                24.2.0
backcall             0.2.0
certifi              2022.12.7
charset-normalizer   3.4.0
click                8.1.7
comm                 0.1.4
ConfigArgParse       1.7
cycler               0.11.0
dash                 2.15.0
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-table           5.0.0
decorator            5.1.1
fastjsonschema       2.21.0
Flask                2.2.5
fonttools            4.38.0
h5py                 3.8.0
idna                 3.10
importlib-metadata   6.7.0
importlib-resources  5.12.0
ipython              7.34.0
ipywidgets           8.1.5
itsdangerous         2.1.2
jedi                 0.19.2
Jinja2               3.1.4
joblib               1.3.2
jsonschema           4.17.3
jupyter_core         4.12.0
jupyterlab_widgets   3.0.13
k3d                  2.16.1
kiwisolver           1.4.5
MarkupSafe           2.1.5
matplotlib           3.5.3
matplotlib-inline    0.1.6
mkl-fft              1.3.1
mkl-random           1.2.2
mkl-service          2.4.0
msgpack              1.0.5
nbformat             5.7.0
nest-asyncio         1.6.0
numpy                1.21.6
open3d               0.17.0
opencv-python        4.10.0.84
packaging            24.0
pandas               1.3.5
parso                0.8.4
pexpect              4.9.0
pickleshare          0.7.5
Pillow               9.5.0
pip                  22.3.1
pkgutil_resolve_name 1.3.10
plotly               5.18.0
pointnet2            0.0.0
prompt_toolkit       3.0.48
ptyprocess           0.7.0
Pygments             2.17.2
pyparsing            3.1.4
pyquaternion         0.9.9
pyrsistent           0.19.3
python-dateutil      2.9.0.post0
pytz                 2024.2
PyYAML               6.0.1
requests             2.31.0
retrying             1.3.4
scikit-learn         1.0.2
scipy                1.7.3
setuptools           65.6.3
six                  1.16.0
tenacity             8.2.3
threadpoolctl        3.1.0
torch                1.7.0
torchaudio           0.7.0a0+ac17b64
torchvision          0.8.0
tqdm                 4.67.1
traitlets            5.9.0
traittypes           0.2.1
typing_extensions    4.7.1
ujson                5.7.0
urllib3              2.0.7
vod-tudelft          1.0.3
wcwidth              0.2.13
Werkzeug             2.2.3
wheel                0.38.4
widgetsnbextension   4.0.13
zipp                 3.15.0

Running the program in Ubuntu 18.04 with python3.7 and cuda11.1
I have followed the instructions in GETTING_STARTED.md.
Thank you for your help.

**Comment by Toytiny** [comment]
This issue should be caused by some noisy samples in our last version dataset. Please re-download our latest dataset and overwrite the data in your local machine.

**Comment by xlbjy** [comment]
@Toytiny @Emery-Wang  Hi, where can I download the latest dataset? The dataset I downloaded from the current Google link (https://drive.google.com/file/d/1Cz8FPGvEDOIBayTP58k1fNu9YZyHcJ42/view) for testing runs up to the 2906th sample and still gives me the selected index k out of range error.
