### ISSUE TITLE
About evaluation

### ISSUE THREAD

**Issue by xlbjy** [Toytiny/milliFlow#9]
Hi, where can I download the latest dataset? The dataset I downloaded from the current Google link (https://drive.google.com/file/d/1Cz8FPGvEDOIBayTP58k1fNu9YZyHcJ42/view) for testing runs up to the 2906th sample and still gives me the selected index k out of range error. #6

**Comment by Lan555** [comment]
please try to download this version of dataset for experiments (https://drive.google.com/file/d/1cfIdR63Plt546mOiHxGMlgg2cgy4a_HL/view?usp=drive_link).
